language: java
jdk:
- oraclejdk8
install:
- true
stages:
- test
- name: deploy
  if: branch =~ ^draft OR tag =~ ^v
jobs:
  include:
  - stage: test
    script: "./gradlew test -x signArchives"
  - stage: deploy
    script:
    - "./gradlew uploadArchives"
before_install:
- openssl aes-256-cbc -K $encrypted_7dc6dfcf9ba9_key -iv $encrypted_7dc6dfcf9ba9_iv
  -in oss_secring.gpg.enc -out ~\/.gnupg/oss_secring.gpg -d
- openssl aes-256-cbc -K $encrypted_7dc6dfcf9ba9_key -iv $encrypted_7dc6dfcf9ba9_iv
  -in oss_secring.gpg.enc -out oss_secring.gpg -d
